import torch
bs = 8
hidden = 100
k = 3
tensor = torch.randn(bs,hidden) 

#if index tensor has the same first dimension as BS
index = torch.randint(hidden, (bs, k))
result = tensor[torch.arange(index.size(0).unsqueeze(1),index]
                             
                             
#if index is generated by a where condition
threshold = 0.5
mask = tensor>=threshold
index = mask.nonzero()#[N,2]
index_t = index.transpose(1,0)
result = tensor([index_t[0],index_t[1]])
                             
                             
                         
